<h4>import lib</h4>

In [7]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats

<h4>Z-Test</h4>

In [15]:
# Given values for z -test
mean_new_drug = 10  #mean improvement for new drop grop
mean_placebo=5
std_new_drug=5
std_placebo=5
n_new_drug=50
n_placebo=50


#calculate the z-score
z=(mean_new_drug-mean_placebo)/np.sqrt(
    (std_new_drug**2/n_new_drug)+(std_placebo**2/n_placebo))

#calculate the p-value(two-tailed-test)
p_value=2*(1-stats.norm.cdf(abs(z)))

#output the results
print(f"Z=score: {z}")
print(f"P-value: {p_value}")

#decision based on a significance level(alpha)
alpha=0.05
if p_value<alpha:
    print("Rejected the null hypothesis (significant difference between the groups)")
else:
    print("fail to reject the null hypothesis (no significant difference between the groups)")

Z=score: 5.0
P-value: 5.733031438470704e-07
Rejected the null hypothesis (significant difference between the groups)


<h4>new data</h4>

In [24]:
#sample data - avg population weight is kgs
data=[78,62,80,75,61,74,79,93,77,95,67,88,54,69]

In [28]:
#define the null hypothesis(avf population weight=80)
null_mean=80

In [30]:
len(data)

14

In [32]:
#calculate the sample mean and std
sample_mean=np.mean(data)
sample_std=np.std(data)

In [34]:
sample_mean

75.14285714285714

In [36]:
sample_std

11.506874608915581

In [38]:
#calculate z score
z_score=(sample_mean-null_mean)/sample_std

In [40]:
z_score

-0.4221079156784696

In [42]:
#calculate the two-tailed p-value using the z-score
p_value=2*(1-stats.norm.cdf(abs(z_score)))

In [44]:
p_value

0.6729462504556214

In [46]:
#define significance level (alpha)- commoly used value is 0.05(5%)
alpha=0.05

In [50]:
#Interpretation
if p_value<alpha:
    print("Reject the null hyothesis. the average weight is statistically different from 80 at a significance level of",alpha)
else:
    print("Fail to reject the null hypothesis. there is not enough evidence to conclude the avvg weight is statistically different from 80 at a significant level of",alpha)

Fail to reject the null hypothesis. there is not enough evidence to conclude the avvg weight is statistically different from 80 at a significant level of 0.05


In [52]:
from statsmodels.stats.weightstats import ztest

In [62]:
# enter iq levels for 20 patinents
data = [88, 92, 94,94, 96, 97,97, 97, 99, 99, 105, 109 , 109, 109, 110 ,112,112, 113,114,115]

In [64]:
# perform one sample z- test
ztest(data, value = 100)

(1.5976240527147705, 0.1101266701438426)

<h4>Chi Square test</h4>

In [70]:
from scipy.stats import chi2_contingency
import numpy as np

In [74]:
#defining the table
data=np.array([[207,282,241],[234,242,232]])

In [76]:
data

array([[207, 282, 241],
       [234, 242, 232]])

In [78]:
data.sum(axis=0)

array([441, 524, 473])

In [80]:
data.sum(axis=1)

array([730, 708])

In [82]:
stat,p,dof,expected=chi2_contingency(data)

In [90]:
print(f"Chi-Square Statistic: {stat:.2f}")
print(f"P-value: {p:.10f}")
print(f"Degrees of Freedom: {dof}")
print(f"Expected Frequencies:\n{expected}")

Chi-Square Statistic: 4.54
P-value: 0.1031971405
Degrees of Freedom: 2
Expected Frequencies:
[[223.87343533 266.00834492 240.11821975]
 [217.12656467 257.99165508 232.88178025]]


In [98]:
alpha = 0.05 
print("p value is "+str(p))# Common significance level
if p < alpha:
    print("Reject the null hypothesis ")
else:
    print("Fail to reject the null hypothesis")

p value is 0.1031971404730939
Fail to reject the null hypothesis


<h4>Practice chi square</h4>

In [101]:
df=np.array([[5,10,5],[15,5,0],[5,10,15]])

In [103]:
df

array([[ 5, 10,  5],
       [15,  5,  0],
       [ 5, 10, 15]])

In [107]:
df.sum(axis=0), df.sum(axis=1)

(array([25, 25, 20]), array([20, 20, 30]))

In [109]:
stat,p,dof,expected=chi2_contingency(df)

In [111]:
print(f"Chi-Square Statistic: {stat:.2f}")
print(f"P-value: {p:.10f}")
print(f"Degrees of Freedom: {dof}")
print(f"Expected Frequencies:\n{expected}")

Chi-Square Statistic: 24.79
P-value: 0.0000554023
Degrees of Freedom: 4
Expected Frequencies:
[[ 7.14285714  7.14285714  5.71428571]
 [ 7.14285714  7.14285714  5.71428571]
 [10.71428571 10.71428571  8.57142857]]


In [113]:
alpha = 0.05 
print("p value is "+str(p))# Common significance level
if p < alpha:
    print("Reject the null hypothesis ")
else:
    print("Fail to reject the null hypothesis")

p value is 5.540229051644113e-05
Reject the null hypothesis 


In [134]:
#one more example
da=np.array([[15,5,5],[10,10,15],[2,3,5]])

In [136]:
stat,p,dof,expected=chi2_contingency(da)

In [138]:
alpha = 0.05 
print("p value is "+str(p))# Common significance level
if p < alpha:
    print("Reject the null hypothesis ")
else:
    print("Fail to reject the null hypothesis")

p value is 0.08877028710376675
Fail to reject the null hypothesis


In [140]:
db=np.array([[20,5],[10,15]])

In [142]:
stat,p,dof,expected=chi2_contingency(db)

In [144]:
alpha = 0.05 
print("p value is "+str(p))# Common significance level
if p < alpha:
    print("Reject the null hypothesis ")
else:
    print("Fail to reject the null hypothesis")

p value is 0.0093747684594349
Reject the null hypothesis 
