<h3>Statement-1</h3>

Create two Numpy arrays, a and b, of the same size and filled with random values.Then,perform the following operations on the arrays:
1. add the two arrays together.
2. subtract the two arrays from each other
3. Multiply the two arrays together
4. Divide the two arrays by each other
5. Take the dot product of the two arrays

In [50]:
import numpy as np
from scipy import stats

In [17]:
a=np.random.rand(3,4)
b=np.random.rand(3,4)

In [19]:
a,b

(array([[0.94620343, 0.79395345, 0.44156237, 0.55882297],
        [0.61351181, 0.58238076, 0.33978546, 0.7467673 ],
        [0.06157955, 0.6187387 , 0.19617319, 0.12898142]]),
 array([[0.18611356, 0.23006099, 0.94042726, 0.44219276],
        [0.71410293, 0.30852815, 0.49103583, 0.3913381 ],
        [0.35491012, 0.43636079, 0.79635284, 0.61649442]]))

In [23]:
#addition
addition=a+b
addition

array([[1.13231699, 1.02401444, 1.38198963, 1.00101574],
       [1.32761473, 0.89090891, 0.83082129, 1.1381054 ],
       [0.41648967, 1.0550995 , 0.99252603, 0.74547585]])

In [25]:
#subtract
subtraction=a-b
subtraction

array([[ 0.76008987,  0.56389246, -0.49886489,  0.11663021],
       [-0.10059112,  0.27385261, -0.15125037,  0.3554292 ],
       [-0.29333057,  0.18237791, -0.60017965, -0.487513  ]])

In [27]:
# Multiply
multiplication=a*b
multiplication

array([[0.17610129, 0.18265772, 0.41525729, 0.24710747],
       [0.43811058, 0.17968086, 0.16684684, 0.2922385 ],
       [0.02185521, 0.26999331, 0.15622308, 0.07951633]])

In [29]:
# division
division=a/b
division

array([[5.08401133, 3.4510564 , 0.46953378, 1.26375422],
       [0.85913638, 1.88760981, 0.69197692, 1.9082407 ],
       [0.17350745, 1.4179521 , 0.24633954, 0.20921751]])

In [33]:
#dot product
dot_product=np.dot(a,b.T)
dot_product

array([[1.02112377, 1.3561553 , 1.37841802],
       [0.89792457, 1.07687677, 1.20283667],
       [0.3953297 , 0.38167586, 0.52758792]])

<h3>Statement 2</h3>

Given a Numpy array a, perform the following operations:

1. Find the mean, median,and mode of the array
2. Find the minimum and maximum values in the array
3. find the standard deviation of the array
4. Normalize the array to have a mean of 0 and a standard deviation of 1
5. Find the element-wise square root of the array

In [42]:
size=(3,4)
num=np.random.randint(1,11,size)

In [44]:
num

array([[4, 2, 5, 7],
       [7, 3, 1, 5],
       [5, 5, 6, 8]])

In [46]:
min=np.min(num)
min

1

In [48]:
max=np.max(num)
max

8

In [52]:
mean=np.mean(num)
mean

4.833333333333333

In [54]:
median=np.median(num)
median

5.0

In [68]:
mode = stats.mode(num, axis=None)
mode

ModeResult(mode=5, count=4)

In [75]:
std=num.std()
std

1.9930434571835665

In [92]:
standardization=(num -num.mean())/a.std()
standardization

array([[ -3.15945134, -10.74213454,   0.63189027,   8.21457347],
       [  8.21457347,  -6.95079294, -14.53347615,   0.63189027],
       [  0.63189027,   0.63189027,   4.42323187,  12.00591508]])

4.833333333333333

In [96]:
sqrt_array= np.sqrt(num)
sqrt_array

array([[2.        , 1.41421356, 2.23606798, 2.64575131],
       [2.64575131, 1.73205081, 1.        , 2.23606798],
       [2.23606798, 2.23606798, 2.44948974, 2.82842712]])

<h3>Statement 3</h3>

Statement 3:
Given a numphy array a and a scalar value b, perform the following operations:
1. add the scalar value to all element of the array.
2. subtract the scalar value from all elements of the array.
3. Multiply all elements of the array by the scalar value.
4. Divide all elements of the array by the scalar value.
5. raise all elements of the array to the power of the scalar value.

In [99]:
size=(3,4)
a=np.random.randint(1,11,size)
b=3

In [101]:
a

array([[ 5,  7,  9,  4],
       [ 8,  8,  9, 10],
       [ 2,  2,  1,  1]])

In [103]:
b

3

In [105]:
addition=a+b
addition

array([[ 8, 10, 12,  7],
       [11, 11, 12, 13],
       [ 5,  5,  4,  4]])

In [107]:
subtraction=a-b
subtraction

array([[ 2,  4,  6,  1],
       [ 5,  5,  6,  7],
       [-1, -1, -2, -2]])

In [109]:
multiplication=a*b
multiplication

array([[15, 21, 27, 12],
       [24, 24, 27, 30],
       [ 6,  6,  3,  3]])

In [111]:
division=a/b
division

array([[1.66666667, 2.33333333, 3.        , 1.33333333],
       [2.66666667, 2.66666667, 3.        , 3.33333333],
       [0.66666667, 0.66666667, 0.33333333, 0.33333333]])

In [113]:
power=np.power(a,b)
power

array([[ 125,  343,  729,   64],
       [ 512,  512,  729, 1000],
       [   8,    8,    1,    1]], dtype=int32)

In [118]:
degree=a**b
degree

array([[ 125,  343,  729,   64],
       [ 512,  512,  729, 1000],
       [   8,    8,    1,    1]], dtype=int32)