In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

<h4>Bayees theorem</h4>

In [5]:
df=pd.read_csv('C:/Users/duasp/students/Social_Network_Ads.csv')

FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/duasp/students/Social_Network_Ads.csv'

In [ ]:
df

In [ ]:
#seprating the features and labels
x=df[['Age','EstimatedSalary']]
y=df['Purchased']

In [ ]:
from sklearn.naive_bayes import GaussianNB

In [ ]:
#create the class
nb=GaussianNB()

In [ ]:
#apply the data/train the algo
nb.fit(x,y)

In [ ]:
GaussianNB()

In [ ]:
 print(nb.predict([[44,25000]]))

In [ ]:
new=pd.DataFrame({
    'Age':[46,23,52],
    'EstimatedSalary':[67000,38700,140000]
})

In [ ]:
new

In [ ]:
nb.predict_proba(new)

In [ ]:
probs=nb.predict_proba(new)

In [ ]:
probs.argmax(axis=1)

In [ ]:
new=pd.DataFrame({
    'Age':[46,23,52,22,50,33],
    'EstimatedSalary':[67000,38700,140000,95000,30000,20000]
})

In [ ]:
new

In [ ]:
nb.predict_proba(new)#class0=0 purchased, class1=1 not purchased

In [ ]:
probs=nb.predict_proba(new)

In [ ]:
probs.argmax(axis=1)

<h4>Generate data from standard normal distribution</h4>

In [ ]:
from scipy.stats import norm

In [ ]:
#the following code shows how to generate 100 random samples
#from a normal distribution with mean 0 and std 1:

In [ ]:
samples=norm.rvs(loc=0,scale=1,size=100) #loc=mean  #scale=std, size=how many elements do you want

In [ ]:
samples

In [ ]:
samples.mean()

In [ ]:
samples.std()

In [ ]:
samples.size

In [ ]:
import seaborn as sns

In [ ]:
samples.mean(), np.median(samples)

In [ ]:
sns.kdeplot(samples)

In [ ]:
samples1=norm.rvs(loc=1,scale=3,size=100)

In [ ]:
samples1.mean()

In [ ]:
samples1.std()

In [ ]:
samples1.size

In [ ]:
sns.kdeplot(samples1)

In [ ]:
samples1=norm.rvs(loc=10,scale=5,size=100, random_state=0)

In [ ]:
samples1

In [ ]:
samples1.mean()

In [ ]:
samples1.std()

In [ ]:
sns.kdeplot(samples1)

In [ ]:
import pandas as pd
sna=pd.read_csv('C:/Users/duasp/datasets/Social_Network_Ads.csv')

In [ ]:
sna['EstimatedSalary'].describe()

In [ ]:
samples2=norm.rvs(loc=70000,scale=34000,size=400,random_state=0)

In [ ]:
samples2

In [ ]:
samples2.std(),samples2.mean(),samples2.min(),samples2.max()

In [ ]:
sna['Age'].describe()

In [ ]:
samples3=norm.rvs(loc=37,scale=10,size=400,random_state=0)

In [ ]:
samples3

In [ ]:
samples3.std(),samples3.mean(),samples3.min(),samples3.max()

In [ ]:
sns.kdeplot(samples3)
sns.kdeplot(sna["Age"])
plt.grid()

<h4>Generate data from poisson distribution</h4>

In [ ]:
from scipy.stats import poisson

In [ ]:
mean_customers_per_hour=5

In [ ]:
#generate random sampe of the number of customes that 
#arrive at the store in one hour
number_of_customers=poisson.rvs(mean_customers_per_hour,size=10)

In [ ]:
number_of_customers

In [ ]:
number_of_customers=poisson.rvs(mean_customers_per_hour,size=100,random_state=0)

In [ ]:
number_of_customers

In [ ]:
number_of_customers.mean()

In [ ]:
number_of_customers.min()

In [ ]:
number_of_customers.max()

In [ ]:
sns.kdeplot(number_of_customers)
plt.grid()

In [ ]:
plt.hist(number_of_customers,bins=range(12));

In [ ]:
custs=pd.Series(number_of_customers)

In [ ]:
plt.figure(figsize=(10,10))
plt.pie(custs.value_counts(), labels=custs.value_counts().index,autopct='%2.2f%%');

In [ ]:
data=custs.value_counts().sort_index()

In [ ]:
plt.figure(figsize=(10,9))
plt.grid()
plt.xticks(range(13))
plt.xlabel('No of Customers')
plt.ylabel('Probability')
plt.plot(data.index,data/100, color='#000000',marker='D')


<h4>Simulate classification dataset</h4>

In [82]:
from sklearn.datasets import make_classification

In [83]:
data=make_classification(n_samples=1000,n_features=10,
                         n_classes=3, random_state=0,n_informative=3)

In [86]:
data[0]

array([[ 0.81977872, -1.20991379, -0.72237997, ...,  1.9315086 ,
        -0.21814691,  1.05237936],
       [-0.07984927, -1.33218739,  0.17422297, ...,  3.26132592,
         0.43621003, -0.28409958],
       [ 0.44839833,  1.46752401,  1.62689087, ...,  0.19981144,
         1.06676359, -1.3433499 ],
       ...,
       [ 1.20103859, -0.10644469,  0.64078896, ..., -0.97554353,
         0.86054368, -1.05819738],
       [-0.00434957,  1.73518621,  2.10221005, ..., -1.10254678,
         0.26108418, -0.67642984],
       [-0.25002979, -0.74140137,  1.34020244, ..., -1.03295636,
         1.5214823 , -1.77799078]])

In [88]:
data[1]

array([0, 0, 2, 2, 2, 0, 1, 1, 2, 0, 2, 0, 1, 2, 1, 2, 2, 1, 0, 0, 1, 2,
       2, 0, 1, 0, 1, 0, 0, 2, 0, 2, 0, 2, 2, 1, 2, 1, 1, 0, 2, 0, 2, 0,
       2, 0, 0, 2, 1, 2, 1, 1, 2, 2, 2, 2, 2, 2, 0, 2, 0, 0, 1, 2, 0, 0,
       1, 1, 0, 0, 2, 1, 1, 1, 0, 1, 1, 0, 2, 2, 2, 0, 2, 0, 1, 2, 2, 0,
       2, 1, 2, 0, 0, 2, 0, 0, 0, 1, 1, 0, 0, 1, 2, 2, 2, 1, 2, 2, 1, 1,
       1, 1, 2, 1, 2, 2, 1, 1, 0, 1, 0, 1, 0, 2, 2, 1, 0, 1, 2, 2, 0, 0,
       2, 1, 0, 0, 2, 1, 0, 2, 0, 0, 1, 0, 1, 2, 1, 2, 1, 0, 0, 1, 2, 1,
       2, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 2, 2, 1, 2, 1, 0, 2, 2, 2,
       1, 0, 2, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 2, 2, 1, 0, 2, 0, 2, 2, 0,
       2, 1, 1, 1, 2, 2, 1, 2, 2, 0, 0, 0, 0, 1, 0, 2, 0, 0, 2, 2, 2, 1,
       2, 2, 2, 1, 0, 0, 1, 2, 2, 2, 2, 0, 0, 2, 1, 2, 2, 1, 0, 2, 1, 2,
       2, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 2, 2, 0, 0, 1,
       0, 2, 0, 0, 1, 1, 0, 1, 2, 0, 0, 1, 1, 2, 0, 2, 1, 2, 0, 1, 1, 2,
       2, 1, 1, 0, 2, 2, 2, 2, 1, 0, 2, 0, 2, 1, 1,

In [90]:
df=pd.DataFrame(data=data[0])

In [92]:
df['class']=data[1]

<h4>Simulate classification dataset</h4>

In [96]:
from sklearn.datasets import make_regression

In [114]:
reg_data=make_regression(n_samples=500,n_features=5)

In [116]:
reg_data

(array([[ 0.9912831 , -1.04354599,  1.21384013,  1.42533405, -1.10754152],
        [-0.55221455, -1.34258451,  0.51569317,  1.75476468,  2.01834796],
        [ 0.29731895,  0.62532561,  1.96320006, -0.11860058,  0.3162468 ],
        ...,
        [ 0.34741371,  2.40661194, -3.01082916,  1.39090102,  0.05754368],
        [-0.69438273, -1.1371296 ,  0.21501207,  0.80053832, -0.72419304],
        [-1.14650802,  1.21103838,  1.01912812, -1.09975535, -1.59689096]]),
 array([ 220.34258563,  102.69253449,  155.40229769,   -5.06134327,
         -38.73663637,  -76.6725958 ,   86.15411289, -143.05248895,
         -30.17163468,   45.80080775, -110.37453055,   70.23012425,
         144.68648493,  -94.00946199,  172.89997103, -155.07842368,
         -41.26371502,  251.15670259,    2.8012038 , -374.54735309,
         146.64073558,   11.99561221, -163.08798974,  154.2567064 ,
          35.68411054,  -76.76881786,  -56.15502544,  193.11351076,
        -204.33578544,   36.85821809,  -42.15516389, -132.2

In [118]:
#input data
reg_data[0]

array([[ 0.9912831 , -1.04354599,  1.21384013,  1.42533405, -1.10754152],
       [-0.55221455, -1.34258451,  0.51569317,  1.75476468,  2.01834796],
       [ 0.29731895,  0.62532561,  1.96320006, -0.11860058,  0.3162468 ],
       ...,
       [ 0.34741371,  2.40661194, -3.01082916,  1.39090102,  0.05754368],
       [-0.69438273, -1.1371296 ,  0.21501207,  0.80053832, -0.72419304],
       [-1.14650802,  1.21103838,  1.01912812, -1.09975535, -1.59689096]])

In [120]:
#output data
reg_data[1]

array([ 220.34258563,  102.69253449,  155.40229769,   -5.06134327,
        -38.73663637,  -76.6725958 ,   86.15411289, -143.05248895,
        -30.17163468,   45.80080775, -110.37453055,   70.23012425,
        144.68648493,  -94.00946199,  172.89997103, -155.07842368,
        -41.26371502,  251.15670259,    2.8012038 , -374.54735309,
        146.64073558,   11.99561221, -163.08798974,  154.2567064 ,
         35.68411054,  -76.76881786,  -56.15502544,  193.11351076,
       -204.33578544,   36.85821809,  -42.15516389, -132.29256126,
         50.28244492, -212.63269176,  -78.61630793,  305.05427787,
        -33.68462664,   24.2830099 ,  -52.06482112,  -28.06945333,
        150.43435063, -256.98839229,  -34.63711219,    3.23739696,
        163.08820952,  100.21159957,  269.47367382,   86.52385608,
         79.02548523,  -81.55359695, -120.13818213,  -75.96385431,
       -209.93577966,   36.418449  ,  105.79900401, -195.95273421,
        -98.84711845,  -82.52659146,   47.30487813,   97.16374

In [122]:
df=pd.DataFrame(data=reg_data[0])

In [124]:
df['output']=reg_data[1]

In [126]:
df

0         1         2         3         4      output
0    0.991283 -1.043546  1.213840  1.425334 -1.107542  220.342586
1   -0.552215 -1.342585  0.515693  1.754765  2.018348  102.692534
2    0.297319  0.625326  1.963200 -0.118601  0.316247  155.402298
3    0.323664 -1.386382 -0.212303  0.418649  0.485117   -5.061343
4    0.210941  2.243057 -1.387982 -0.458837 -1.433043  -38.736636
..        ...       ...       ...       ...       ...         ...
495  1.319417 -0.615795 -0.102894  0.164497 -0.368888   67.772396
496  0.525064  0.216298  0.382030 -0.158114  0.533829   52.258905
497  0.347414  2.406612 -3.010829  1.390901  0.057544   30.095080
498 -0.694383 -1.137130  0.215012  0.800538 -0.724193   -3.215764
499 -1.146508  1.211038  1.019128 -1.099755 -1.596891  -60.281408

[500 rows x 6 columns]