In [3]:
import numpy as np
import matplotlib.pyplot as plt

In [5]:
M=np.array([[5,4,3],[1,7,8],[1,5,3],[4,8,9]])

In [14]:
M 

array([[5, 4, 3],
       [1, 7, 8],
       [1, 5, 3],
       [4, 8, 9]])

In [16]:
type(M)

numpy.ndarray

In [20]:
M=np.array([[5,4,3],[1,7,8],[1,5,3],[4,8,9]] , dtype = np.int8)
M

array([[5, 4, 3],
       [1, 7, 8],
       [1, 5, 3],
       [4, 8, 9]], dtype=int8)

In [24]:
M.shape

(4, 3)

In [30]:
M.size

12

In [32]:
M.diagonal()

array([5, 7, 3], dtype=int8)

In [34]:
M.ndim

2

In [38]:
M[0]

array([5, 4, 3], dtype=int8)

In [40]:
M

array([[5, 4, 3],
       [1, 7, 8],
       [1, 5, 3],
       [4, 8, 9]], dtype=int8)

In [44]:
M[1,2]=2

In [46]:
M

array([[5, 4, 3],
       [1, 7, 2],
       [1, 5, 3],
       [4, 8, 9]], dtype=int8)

In [50]:
M.reshape(3,4)

array([[5, 4, 3, 1],
       [7, 2, 1, 5],
       [3, 4, 8, 9]], dtype=int8)

In [52]:
M.reshape(12,1)

array([[5],
       [4],
       [3],
       [1],
       [7],
       [2],
       [1],
       [5],
       [3],
       [4],
       [8],
       [9]], dtype=int8)

In [54]:
M.reshape(6,2)

array([[5, 4],
       [3, 1],
       [7, 2],
       [1, 5],
       [3, 4],
       [8, 9]], dtype=int8)

In [56]:
M.reshape(-1,2)

array([[5, 4],
       [3, 1],
       [7, 2],
       [1, 5],
       [3, 4],
       [8, 9]], dtype=int8)

In [58]:
M.reshape(-1)

array([5, 4, 3, 1, 7, 2, 1, 5, 3, 4, 8, 9], dtype=int8)

In [60]:
M

array([[5, 4, 3],
       [1, 7, 2],
       [1, 5, 3],
       [4, 8, 9]], dtype=int8)

In [66]:
#one d
M.flatten()

array([5, 4, 3, 1, 7, 2, 1, 5, 3, 4, 8, 9], dtype=int8)

In [80]:
v1=np.array([1,2,3,4,5,6,7,8,9])

In [82]:
v1.reshape(3,3).transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [76]:
np.arange(1,10).reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [92]:
M.astype(np.float16)

array([[5., 4., 3.],
       [1., 7., 2.],
       [1., 5., 3.],
       [4., 8., 9.]], dtype=float16)

In [96]:
M.astype(np.bool_)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [102]:
matrix=[]

for i in range(3):
    rows=[]
    for j in range(3):
        rows.append((i+1)*(j+1))
    matrix.append(rows)

for row in matrix:
    print(row)

        

[1, 2, 3]
[2, 4, 6]
[3, 6, 9]


In [117]:
for i in range(3):
    for j in range(3):
        print(M[i][j],  end =' ')
    print()


5 4 3 
1 7 2 
1 5 3 


In [ ]:
# #for row in M:
#     for value in row:
#         print(value,end=' ')
#     print()

In [124]:
np.median(M)

4.0

In [128]:
M.sum()

52

In [132]:
Z=np.zeros([3,3])
Z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [134]:
O=np.ones([4,4])
O

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [139]:
O.sum()


16.0

In [145]:
S = np.arange(15).reshape(3,5)

In [147]:
S

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [159]:
S[1:3, 1:2]

array([[ 6],
       [11]])

In [191]:
M1=np.array([[6,8,7],[4,1,3],[5,2,9]])

In [193]:
M1

array([[6, 8, 7],
       [4, 1, 3],
       [5, 2, 9]])

In [195]:
for i in range(M1.shape[0]):
    for j in range(M1.shape[1]):
        if M1[i][j]%2==1:#0 for even
            M1[i][j]=0
            


    
    

In [197]:
M1

array([[6, 8, 0],
       [4, 0, 0],
       [0, 2, 0]])

In [278]:
M1=np.array([[5,4,3],[1,7,8],[0,2,3],[7,5,1]])#unsigned integer
M2=np.array([[2,8,1],[0,2,5],[1,9,4],[6,2,6]])

In [231]:
M1.shape,M2.shape

((4, 3), (4, 3))

In [233]:
M3=M1-M2
M3

array([[  3, 252,   2],
       [  1,   5,   3],
       [255, 249, 255],
       [  1,   3, 251]], dtype=uint8)

In [235]:
M1+10

array([[15, 14, 13],
       [11, 17, 18],
       [10, 12, 13],
       [17, 15, 11]], dtype=uint8)

In [237]:
M1*2

array([[10,  8,  6],
       [ 2, 14, 16],
       [ 0,  4,  6],
       [14, 10,  2]], dtype=uint8)

In [248]:
M1

array([[5, 4, 3],
       [1, 7, 8],
       [0, 2, 3],
       [7, 5, 1]], dtype=uint8)

In [250]:
M

array([[5, 4, 3],
       [1, 7, 2],
       [1, 5, 3],
       [4, 8, 9]], dtype=int8)

In [252]:
3 * M

array([[15, 12,  9],
       [ 3, 21,  6],
       [ 3, 15,  9],
       [12, 24, 27]], dtype=int8)

In [254]:
M1

array([[5, 4, 3],
       [1, 7, 8],
       [0, 2, 3],
       [7, 5, 1]], dtype=uint8)

In [256]:
M2

array([[2, 8, 1],
       [0, 2, 5],
       [1, 9, 4],
       [6, 2, 6]], dtype=uint8)

In [260]:
3* (M1 + M2)

array([[21, 36, 12],
       [ 3, 27, 39],
       [ 3, 33, 21],
       [39, 21, 21]], dtype=uint8)

In [262]:
(3 + 4) * M1

array([[35, 28, 21],
       [ 7, 49, 56],
       [ 0, 14, 21],
       [49, 35,  7]], dtype=uint8)

In [264]:
 3 * M1 + 4 * M1

array([[35, 28, 21],
       [ 7, 49, 56],
       [ 0, 14, 21],
       [49, 35,  7]], dtype=uint8)

In [266]:
3 * 4 * M1

array([[60, 48, 36],
       [12, 84, 96],
       [ 0, 24, 36],
       [84, 60, 12]], dtype=uint8)

In [270]:
3 * 4 * M1, 4 *(M1 * 3), M1 * (4 * 3)

(array([[60, 48, 36],
        [12, 84, 96],
        [ 0, 24, 36],
        [84, 60, 12]], dtype=uint8),
 array([[60, 48, 36],
        [12, 84, 96],
        [ 0, 24, 36],
        [84, 60, 12]], dtype=uint8),
 array([[60, 48, 36],
        [12, 84, 96],
        [ 0, 24, 36],
        [84, 60, 12]], dtype=uint8))

In [280]:
-3 * M1

array([[-15, -12,  -9],
       [ -3, -21, -24],
       [  0,  -6,  -9],
       [-21, -15,  -3]])

In [282]:
-(3 * M1)

array([[-15, -12,  -9],
       [ -3, -21, -24],
       [  0,  -6,  -9],
       [-21, -15,  -3]])

In [284]:
-1 * M1

array([[-5, -4, -3],
       [-1, -7, -8],
       [ 0, -2, -3],
       [-7, -5, -1]])

In [288]:
####3 Mtrix Multiplication
#matmul()

In [299]:
M1=np.array([[5,4,3],
     [1,7,8]])
M2=np.array([[2,8],
     [1,0],
     [2,5]])

In [301]:
np.matmul(M1,M2)


array([[20, 55],
       [25, 48]])

In [307]:
A=np.array([[1,2],[3,4]])
B=np.array([[4,6],[6,2]])
C=np.array([[9,3],[6,8]])

In [311]:
A@ (B@C),(A@B)@C

(array([[204, 128],
        [480, 316]]),
 array([[204, 128],
        [480, 316]]))

In [317]:
M1 @ M2,M2 @ M1

(array([[20, 55],
        [25, 48]]),
 array([[18, 64, 70],
        [ 5,  4,  3],
        [15, 43, 46]]))

In [323]:
A @ ( B + C), A@B+A@C

(array([[37, 29],
        [87, 67]]),
 array([[37, 29],
        [87, 67]]))

In [325]:
(A + B) @ C, A@ C + B @ C

(array([[ 93,  79],
        [117,  75]]),
 array([[ 93,  79],
        [117,  75]]))

In [327]:
M1

array([[5, 4, 3],
       [1, 7, 8]])

In [329]:
M1.transpose()

array([[5, 1],
       [4, 7],
       [3, 8]])

In [331]:
M1.T

array([[5, 1],
       [4, 7],
       [3, 8]])

In [343]:
M2,M2.T.T

(array([[2, 8],
        [1, 0],
        [2, 5]]),
 array([[2, 8],
        [1, 0],
        [2, 5]]))

In [356]:
A.T +B.T, (A+B).T.T

(array([[5, 9],
        [8, 6]]),
 array([[5, 8],
        [9, 6]]))

In [360]:
(3 * A). T, 3 * A.T.T

(array([[ 3,  9],
        [ 6, 12]]),
 array([[ 3,  6],
        [ 9, 12]]))

In [362]:
(A @ B) .T , B.T @  A.T

(array([[16, 36],
        [10, 26]]),
 array([[16, 36],
        [10, 26]]))

In [431]:
rows=int(input("enter number of rows: "))
cols=int(input("enter number of columns: "))
M = np.zeros([rows,cols],dtype=np.int16)
for i in range(rows):
    for j in range(cols):
        num=int(input('enter values '))
        M[i,j]=num

print("original Matrix: \n",M)
print("transpose of it is \n:",M.T)

enter number of rows:  2
enter number of columns:  3
enter values  1
enter values  2
enter values  3
enter values  4
enter values  5
enter values  6


original Matrix: 
 [[1 2 3]
 [4 5 6]]
transpose of it is 
: [[1 4]
 [2 5]
 [3 6]]


In [441]:
M2=np.array([[2,8,1],
             [0,2,5],
             [1,9,4]],dtype=np.int8)

c=M2.diagonal()
c.sum()

8

In [459]:
add=0
for i in range(min(M2.shape)):
    add=M2[i,i]+add

add

8

In [461]:
add = 0
for i in range(min(M1.shape)):
    add = M1[i, i] + add

add

12

In [475]:
M2.diagonal().sum()


8

In [477]:
M2.diagonal().sum()

8

In [489]:
M1.trace(),M2.trace()

(12, 8)

In [493]:
np.trace(A @ B) , np.trace(B @ A)

(42, 42)

In [498]:
M1.trace(), M1.T.trace()

(12, 12)

In [504]:
np.trace(M1*3), 3*M1.trace()

(36, 36)

In [506]:
A.trace() +B.trace(),  np.trace(A+B)

(11, 11)

In [508]:
M2

array([[2, 8, 1],
       [0, 2, 5],
       [1, 9, 4]], dtype=int8)

In [510]:
np.linalg.det(M2)

-36.0

In [523]:
M2

array([[2, 8, 1],
       [0, 2, 5],
       [1, 9, 4]], dtype=int8)

In [525]:
np.linalg.inv(M2)

array([[ 1.02777778,  0.63888889, -1.05555556],
       [-0.13888889, -0.19444444,  0.27777778],
       [ 0.05555556,  0.27777778, -0.11111111]])

In [527]:
 M1

array([[5, 4, 3],
       [1, 7, 8]])

In [530]:
M3

array([[  3, 252,   2],
       [  1,   5,   3],
       [255, 249, 255],
       [  1,   3, 251]], dtype=uint8)

In [532]:
M2

array([[2, 8, 1],
       [0, 2, 5],
       [1, 9, 4]], dtype=int8)

In [538]:
np.linalg.matrix_rank(M2)

3

In [552]:
M4=np.array([[17,33,22],[2,4,6],[3,6,9]])

In [554]:
np.linalg.matrix_rank(M4)

2

In [555]:
M4

array([[17, 33, 22],
       [ 2,  4,  6],
       [ 3,  6,  9]])

In [563]:
R=np.array([[3,4,5],[1,3,8]])

In [565]:
R.reshape(1,-1)

array([[3, 4, 5, 1, 3, 8]])

In [567]:
C=np.array([[3,4,5],[1,3,8]])

In [591]:
CR=C.reshape(-1,1)

In [593]:
CR

array([[3],
       [4],
       [5],
       [1],
       [3],
       [8]])

In [595]:
CR.T

array([[3, 4, 5, 1, 3, 8]])

In [597]:
#square matrix

In [636]:
S=np.array([[3,4,5,3],[1,3,8,2],[9,0,2,5]])

In [638]:
S

array([[3, 4, 5, 3],
       [1, 3, 8, 2],
       [9, 0, 2, 5]])

In [644]:
def isSquareMatrix(M):
    if M.shape[0]==M.shape[1]:
        return True
    else:
        return False

In [642]:
isSquareMatrix(S)

False

In [653]:
def isRectangularMatrix(M):
    if M.shape[0]!=M.shape[1]:
        return True
    else:
        return False

In [656]:
isSquareMatrix(S)

False

In [658]:
#####Diagonal Matrix

In [687]:
np.random.randint(1,10)

3

In [717]:
rows=int(input("enter number of rows: "))

matrix=np.zeros([rows,rows],dtype=np.int16)
for i in range(rows):
   matrix[i,i]= np.random.randint(1,10)
   

matrix


enter number of rows:  5


array([[8, 0, 0, 0, 0],
       [0, 5, 0, 0, 0],
       [0, 0, 4, 0, 0],
       [0, 0, 0, 8, 0],
       [0, 0, 0, 0, 2]], dtype=int16)

In [727]:
def isDiagonalMatrix(M):
    if(M>0).flatten().sum()==M.shape[0]:
        return True
    else:
        return False
        
                
                
                

In [729]:
isDiagonalMatrix(M)

False

In [731]:
isDiagonalMatrix(S)

False

In [737]:
##identity matrix

In [745]:
I = np.zeros([4,4], dtype = np.int16)

In [747]:
I

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int16)

In [753]:
rc = int(input("Enter number:"))
I = np.zeros([rc,rc],dtype= np.int16)
for i in range(rc):
 I[i,i] = 1
I

Enter number: 4


array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]], dtype=int16)

In [755]:
def isIdentity(M):
    if M.flatten().sum() == M.shape[0]:
        return True
    else:
        return False

In [761]:
##Symmetric Matrix

In [824]:
S = np.array([[2,3,6],[3,4,5],[6,5,9]], dtype = np.int16)

In [826]:
S

array([[2, 3, 6],
       [3, 4, 5],
       [6, 5, 9]], dtype=int16)

In [829]:
def isSymmetricMatrix(M):
    if (M == M.T).flatten().sum() == M.size():
         return True
    else:
        return False
    

In [1]:
###isSymmetricMatrix(S)

In [818]:
M

array([[1, 2, 3],
       [4, 5, 6]], dtype=int16)

In [820]:
M

array([[1, 2, 3],
       [4, 5, 6]], dtype=int16)

In [822]:
M.T

array([[1, 4],
       [2, 5],
       [3, 6]], dtype=int16)

In [835]:
S1=np.array([[0,3],[-3,0]],dtype=np.int16)


In [837]:
S1

array([[ 0,  3],
       [-3,  0]], dtype=int16)

In [839]:
def isSkewMatrix(M):
    if (M == M.T).flatten().sum() == M.size():
         return True
    else:
        return False




In [841]:
###3 Orthogonal Matrix

In [844]:
I

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]], dtype=int16)

In [846]:
I.T

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]], dtype=int16)

In [848]:
np.linalg.inv(I)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [858]:
RM = np.array([[np.cos(50), -np.sin(50)],[np.sin(50), np.cos(50 )]])

In [862]:
RM

array([[ 0.96496603,  0.26237485],
       [-0.26237485,  0.96496603]])

In [864]:
RM.T

array([[ 0.96496603, -0.26237485],
       [ 0.26237485,  0.96496603]])

In [866]:
np.linalg.inv(RM)

array([[ 0.96496603, -0.26237485],
       [ 0.26237485,  0.96496603]])

In [878]:
####Permutatun Matrix

In [870]:
P = np.array([[0,1,0],[1,0,0],[0,0,1]], dtype = np.int16)

In [872]:
P

array([[0, 1, 0],
       [1, 0, 0],
       [0, 0, 1]], dtype=int16)

In [874]:
P.T

array([[0, 1, 0],
       [1, 0, 0],
       [0, 0, 1]], dtype=int16)

In [876]:
np.linalg.inv(P)

array([[0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.]])

In [884]:
M5 = np.array([[5,6,4,2],[1,2,3,4],[7,8,9,0],[6,5,3,4]])

In [886]:
M5

array([[5, 6, 4, 2],
       [1, 2, 3, 4],
       [7, 8, 9, 0],
       [6, 5, 3, 4]])

In [890]:
M5 @ I

array([[5, 6, 4, 2],
       [1, 2, 3, 4],
       [7, 8, 9, 0],
       [6, 5, 3, 4]])

In [892]:
###3EigenValues

In [898]:
A = np.array([[1,2],[3,4]], dtype = np.int8)

In [906]:
value, vector = np.linalg.eig(A)

In [908]:
value

array([-0.37228132,  5.37228132])

In [910]:
vector

array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]])

In [912]:
A @ vector

array([[ 0.30697009, -2.23472698],
       [-0.21062466, -4.88542751]])

In [914]:
value * vector

array([[ 0.30697009, -2.23472698],
       [-0.21062466, -4.88542751]])

In [916]:
A = np.array([[1,2,3,4],[3,4,5,6],[3,7,8,9],[1,2,3,4]], dtype = np.int8)

In [918]:
A

array([[1, 2, 3, 4],
       [3, 4, 5, 6],
       [3, 7, 8, 9],
       [1, 2, 3, 4]], dtype=int8)

In [920]:
value , vector = np.linalg.eig(A)

In [922]:
A

array([[1, 2, 3, 4],
       [3, 4, 5, 6],
       [3, 7, 8, 9],
       [1, 2, 3, 4]], dtype=int8)

In [924]:
vector.dtype

dtype('complex128')

In [926]:
vector

array([[-2.79595679e-01+0.j        , -2.77280362e-01-0.19087204j,
        -2.77280362e-01+0.19087204j, -3.40271307e-16+0.j        ],
       [-4.96720275e-01+0.j        , -3.34019522e-01+0.38766109j,
        -3.34019522e-01-0.38766109j,  4.08248290e-01+0.j        ],
       [-7.72606938e-01+0.j        ,  7.15204006e-01+0.j        ,
         7.15204006e-01-0.j        , -8.16496581e-01+0.j        ],
       [-2.79595679e-01+0.j        , -2.77280362e-01-0.19087204j,
        -2.77280362e-01+0.19087204j,  4.08248290e-01+0.j        ]])